feat/#61_added_dynamic_navigation
UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit pull request #81
Opened 2021-02-11 15:13 UTC by orembold

Closes #61

2021-02-11 15:27 UTC, cetceeve commented
closes #78

2021-02-11 15:28 UTC, cetceeve commented
No conflicts with any previous work. :) Will perform full review later today or tomorrow.

2021-02-11 15:45 UTC, Naarij requested changes
Great work overall - just some minor polishing on style.
I really like the way, the data is now organized. I'll leave the pr on request changes for the minro polishing stuff. Afterwards I will approve. I think some tests should be added to for this use case but this can be done later.

2021-02-11 15:45 UTC, Naarij commented on src/App.js
> +              path="/category/:category"
Just tested out and works - BUT: also creates a path with "/favorites/1". With sharing links among different users this might cause problems.

2021-02-11 15:45 UTC, Naarij commented on src/components/pageComponents/ExpandableListItem.js
> +        {open ? (
Generally I am a fan of ternary operators - but in this case I would prefer a normal if.
Imo i would only user ternary operatos on small statements which can be expressed in one line. But would also like to hear the opinion of @cetceeve on this.

2021-02-11 15:45 UTC, Naarij commented on src/components/pages/CategoryList.js
> +import { List, ListItem, ListItemText, withStyles } from "@material-ui/core/";
Linebreaks for multiple imports

2021-02-11 15:45 UTC, Naarij commented on src/components/pageComponents/ExpandableListItem.js
> +import { ExpandLess, ExpandMore } from "@material-ui/icons/";
Linebreaks for multiple imports (even for two - I think we should keep it consistent)

2021-02-11 15:45 UTC, Naarij commented on src/components/pages/Contentlistscreen.js
>  import { ArrowBack as ArrowBackIcon } from "@material-ui/icons";
Linebreaks for multiple imports

2021-02-11 19:03 UTC, cetceeve approved these changes
Awesome solution! Works like a charm! 😄 

Will be interesting to see how this changes once we have a datamodel, because the constants file is crazy right now.

2021-02-11 19:03 UTC, cetceeve commented on src/components/pageComponents/ContentCard.js
> +    : `/favorites/${data.id}`;
Can you explain how this works? Cant wrap my head around it... 😅

2021-02-12 13:46 UTC, cetceeve approved these changes

2021-02-12 14:27 UTC, Naarij approved these changes

2021-02-12 14:48 UTC, merged